// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usercmd.proto

#include "usercmd.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CSubtickMoveStep::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        button_{::uint64_t{0u}},
        pressed_{false},
        when_{0},
        analog_forward_delta_{0},
        analog_left_delta_{0},
        pitch_delta_{0},
        yaw_delta_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CSubtickMoveStep::CSubtickMoveStep(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CSubtickMoveStepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSubtickMoveStepDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSubtickMoveStepDefaultTypeInternal() {}
  union {
    CSubtickMoveStep _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSubtickMoveStepDefaultTypeInternal _CSubtickMoveStep_default_instance_;

inline constexpr CInButtonStatePB::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        buttonstate1_{::uint64_t{0u}},
        buttonstate2_{::uint64_t{0u}},
        buttonstate3_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR CInButtonStatePB::CInButtonStatePB(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CInButtonStatePBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CInButtonStatePBDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CInButtonStatePBDefaultTypeInternal() {}
  union {
    CInButtonStatePB _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CInButtonStatePBDefaultTypeInternal _CInButtonStatePB_default_instance_;

inline constexpr CBaseUserCmdExecutionNotes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ignored_reason_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CBaseUserCmdExecutionNotes::CBaseUserCmdExecutionNotes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CBaseUserCmdExecutionNotesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CBaseUserCmdExecutionNotesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CBaseUserCmdExecutionNotesDefaultTypeInternal() {}
  union {
    CBaseUserCmdExecutionNotes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CBaseUserCmdExecutionNotesDefaultTypeInternal _CBaseUserCmdExecutionNotes_default_instance_;

inline constexpr CBaseUserCmdPB::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        subtick_moves_{},
        move_crc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        buttons_pb_{nullptr},
        viewangles_{nullptr},
        execution_notes_{nullptr},
        legacy_command_number_{0},
        client_tick_{0},
        forwardmove_{0},
        leftmove_{0},
        upmove_{0},
        impulse_{0},
        weaponselect_{0},
        random_seed_{0},
        mousedx_{0},
        mousedy_{0},
        prediction_offset_ticks_x256_{0u},
        consumed_server_angle_changes_{0u},
        cmd_flags_{0},
        pawn_entity_handle_{16777215u} {}

template <typename>
PROTOBUF_CONSTEXPR CBaseUserCmdPB::CBaseUserCmdPB(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CBaseUserCmdPBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CBaseUserCmdPBDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CBaseUserCmdPBDefaultTypeInternal() {}
  union {
    CBaseUserCmdPB _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CBaseUserCmdPBDefaultTypeInternal _CBaseUserCmdPB_default_instance_;

inline constexpr CUserCmdBasePB::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        base_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CUserCmdBasePB::CUserCmdBasePB(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CUserCmdBasePBDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CUserCmdBasePBDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CUserCmdBasePBDefaultTypeInternal() {}
  union {
    CUserCmdBasePB _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CUserCmdBasePBDefaultTypeInternal _CUserCmdBasePB_default_instance_;
static ::_pb::Metadata file_level_metadata_usercmd_2eproto[5];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_usercmd_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_usercmd_2eproto = nullptr;
const ::uint32_t TableStruct_usercmd_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_.buttonstate1_),
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_.buttonstate2_),
    PROTOBUF_FIELD_OFFSET(::CInButtonStatePB, _impl_.buttonstate3_),
    0,
    1,
    2,
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.button_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.pressed_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.when_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.analog_forward_delta_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.analog_left_delta_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.pitch_delta_),
    PROTOBUF_FIELD_OFFSET(::CSubtickMoveStep, _impl_.yaw_delta_),
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdExecutionNotes, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdExecutionNotes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdExecutionNotes, _impl_.ignored_reason_),
    0,
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.legacy_command_number_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.client_tick_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.prediction_offset_ticks_x256_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.buttons_pb_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.viewangles_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.forwardmove_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.leftmove_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.upmove_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.impulse_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.weaponselect_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.random_seed_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.mousedx_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.mousedy_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.pawn_entity_handle_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.subtick_moves_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.move_crc_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.consumed_server_angle_changes_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.cmd_flags_),
    PROTOBUF_FIELD_OFFSET(::CBaseUserCmdPB, _impl_.execution_notes_),
    4,
    5,
    14,
    1,
    2,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    17,
    ~0u,
    0,
    15,
    16,
    3,
    PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CUserCmdBasePB, _impl_.base_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::CInButtonStatePB)},
        {14, 29, -1, sizeof(::CSubtickMoveStep)},
        {36, 45, -1, sizeof(::CBaseUserCmdExecutionNotes)},
        {46, 73, -1, sizeof(::CBaseUserCmdPB)},
        {92, 101, -1, sizeof(::CUserCmdBasePB)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_CInButtonStatePB_default_instance_._instance,
    &::_CSubtickMoveStep_default_instance_._instance,
    &::_CBaseUserCmdExecutionNotes_default_instance_._instance,
    &::_CBaseUserCmdPB_default_instance_._instance,
    &::_CUserCmdBasePB_default_instance_._instance,
};
const char descriptor_table_protodef_usercmd_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rusercmd.proto\032\026networkbasetypes.proto\""
    "T\n\020CInButtonStatePB\022\024\n\014buttonstate1\030\001 \001("
    "\004\022\024\n\014buttonstate2\030\002 \001(\004\022\024\n\014buttonstate3\030"
    "\003 \001(\004\"\242\001\n\020CSubtickMoveStep\022\016\n\006button\030\001 \001"
    "(\004\022\017\n\007pressed\030\002 \001(\010\022\014\n\004when\030\003 \001(\002\022\034\n\024ana"
    "log_forward_delta\030\004 \001(\002\022\031\n\021analog_left_d"
    "elta\030\005 \001(\002\022\023\n\013pitch_delta\030\010 \001(\002\022\021\n\tyaw_d"
    "elta\030\t \001(\002\"4\n\032CBaseUserCmdExecutionNotes"
    "\022\026\n\016ignored_reason\030\001 \001(\t\"\231\004\n\016CBaseUserCm"
    "dPB\022\035\n\025legacy_command_number\030\001 \001(\005\022\023\n\013cl"
    "ient_tick\030\002 \001(\005\022$\n\034prediction_offset_tic"
    "ks_x256\030\021 \001(\r\022%\n\nbuttons_pb\030\003 \001(\0132\021.CInB"
    "uttonStatePB\022\037\n\nviewangles\030\004 \001(\0132\013.CMsgQ"
    "Angle\022\023\n\013forwardmove\030\005 \001(\002\022\020\n\010leftmove\030\006"
    " \001(\002\022\016\n\006upmove\030\007 \001(\002\022\017\n\007impulse\030\010 \001(\005\022\024\n"
    "\014weaponselect\030\t \001(\005\022\023\n\013random_seed\030\n \001(\005"
    "\022\017\n\007mousedx\030\013 \001(\005\022\017\n\007mousedy\030\014 \001(\005\022$\n\022pa"
    "wn_entity_handle\030\016 \001(\r:\01016777215\022(\n\rsubt"
    "ick_moves\030\022 \003(\0132\021.CSubtickMoveStep\022\020\n\010mo"
    "ve_crc\030\023 \001(\014\022%\n\035consumed_server_angle_ch"
    "anges\030\024 \001(\r\022\021\n\tcmd_flags\030\025 \001(\005\0224\n\017execut"
    "ion_notes\030\026 \001(\0132\033.CBaseUserCmdExecutionN"
    "otes\"/\n\016CUserCmdBasePB\022\035\n\004base\030\001 \001(\0132\017.C"
    "BaseUserCmdPB"
};
static const ::_pbi::DescriptorTable* const descriptor_table_usercmd_2eproto_deps[1] =
    {
        &::descriptor_table_networkbasetypes_2eproto,
};
static ::absl::once_flag descriptor_table_usercmd_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_usercmd_2eproto = {
    false,
    false,
    933,
    descriptor_table_protodef_usercmd_2eproto,
    "usercmd.proto",
    &descriptor_table_usercmd_2eproto_once,
    descriptor_table_usercmd_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_usercmd_2eproto::offsets,
    file_level_metadata_usercmd_2eproto,
    file_level_enum_descriptors_usercmd_2eproto,
    file_level_service_descriptors_usercmd_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_usercmd_2eproto_getter() {
  return &descriptor_table_usercmd_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_usercmd_2eproto(&descriptor_table_usercmd_2eproto);
// ===================================================================

class CInButtonStatePB::_Internal {
 public:
  using HasBits = decltype(std::declval<CInButtonStatePB>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_._has_bits_);
  static void set_has_buttonstate1(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_buttonstate2(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_buttonstate3(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

CInButtonStatePB::CInButtonStatePB(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CInButtonStatePB)
}
CInButtonStatePB::CInButtonStatePB(
    ::google::protobuf::Arena* arena, const CInButtonStatePB& from)
    : CInButtonStatePB(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CInButtonStatePB::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CInButtonStatePB::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, buttonstate1_),
           0,
           offsetof(Impl_, buttonstate3_) -
               offsetof(Impl_, buttonstate1_) +
               sizeof(Impl_::buttonstate3_));
}
CInButtonStatePB::~CInButtonStatePB() {
  // @@protoc_insertion_point(destructor:CInButtonStatePB)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CInButtonStatePB::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CInButtonStatePB::Clear() {
// @@protoc_insertion_point(message_clear_start:CInButtonStatePB)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.buttonstate1_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.buttonstate3_) -
        reinterpret_cast<char*>(&_impl_.buttonstate1_)) + sizeof(_impl_.buttonstate3_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CInButtonStatePB::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> CInButtonStatePB::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CInButtonStatePB_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint64 buttonstate1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CInButtonStatePB, _impl_.buttonstate1_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate1_)}},
    // optional uint64 buttonstate2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CInButtonStatePB, _impl_.buttonstate2_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate2_)}},
    // optional uint64 buttonstate3 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CInButtonStatePB, _impl_.buttonstate3_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate3_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 buttonstate1 = 1;
    {PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate1_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 buttonstate2 = 2;
    {PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate2_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 buttonstate3 = 3;
    {PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate3_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CInButtonStatePB::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CInButtonStatePB)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint64 buttonstate1 = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_buttonstate1(), target);
  }

  // optional uint64 buttonstate2 = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_buttonstate2(), target);
  }

  // optional uint64 buttonstate3 = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_buttonstate3(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CInButtonStatePB)
  return target;
}

::size_t CInButtonStatePB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CInButtonStatePB)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional uint64 buttonstate1 = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_buttonstate1());
    }

    // optional uint64 buttonstate2 = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_buttonstate2());
    }

    // optional uint64 buttonstate3 = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_buttonstate3());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CInButtonStatePB::_class_data_ = {
    CInButtonStatePB::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CInButtonStatePB::GetClassData() const {
  return &_class_data_;
}

void CInButtonStatePB::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CInButtonStatePB*>(&to_msg);
  auto& from = static_cast<const CInButtonStatePB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CInButtonStatePB)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.buttonstate1_ = from._impl_.buttonstate1_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.buttonstate2_ = from._impl_.buttonstate2_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.buttonstate3_ = from._impl_.buttonstate3_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CInButtonStatePB::CopyFrom(const CInButtonStatePB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CInButtonStatePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CInButtonStatePB::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CInButtonStatePB::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CInButtonStatePB::InternalSwap(CInButtonStatePB* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate3_)
      + sizeof(CInButtonStatePB::_impl_.buttonstate3_)
      - PROTOBUF_FIELD_OFFSET(CInButtonStatePB, _impl_.buttonstate1_)>(
          reinterpret_cast<char*>(&_impl_.buttonstate1_),
          reinterpret_cast<char*>(&other->_impl_.buttonstate1_));
}

::google::protobuf::Metadata CInButtonStatePB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[0]);
}
// ===================================================================

class CSubtickMoveStep::_Internal {
 public:
  using HasBits = decltype(std::declval<CSubtickMoveStep>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_._has_bits_);
  static void set_has_button(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_pressed(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_when(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_analog_forward_delta(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_analog_left_delta(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_pitch_delta(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_yaw_delta(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
};

CSubtickMoveStep::CSubtickMoveStep(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CSubtickMoveStep)
}
CSubtickMoveStep::CSubtickMoveStep(
    ::google::protobuf::Arena* arena, const CSubtickMoveStep& from)
    : CSubtickMoveStep(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CSubtickMoveStep::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CSubtickMoveStep::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, button_),
           0,
           offsetof(Impl_, yaw_delta_) -
               offsetof(Impl_, button_) +
               sizeof(Impl_::yaw_delta_));
}
CSubtickMoveStep::~CSubtickMoveStep() {
  // @@protoc_insertion_point(destructor:CSubtickMoveStep)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CSubtickMoveStep::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CSubtickMoveStep::Clear() {
// @@protoc_insertion_point(message_clear_start:CSubtickMoveStep)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    ::memset(&_impl_.button_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.yaw_delta_) -
        reinterpret_cast<char*>(&_impl_.button_)) + sizeof(_impl_.yaw_delta_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CSubtickMoveStep::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2> CSubtickMoveStep::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_._has_bits_),
    0, // no _extensions_
    9, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966880,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CSubtickMoveStep_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional float pitch_delta = 8;
    {::_pbi::TcParser::FastF32S1,
     {69, 5, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.pitch_delta_)}},
    // optional uint64 button = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CSubtickMoveStep, _impl_.button_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.button_)}},
    // optional bool pressed = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CSubtickMoveStep, _impl_.pressed_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.pressed_)}},
    // optional float when = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.when_)}},
    // optional float analog_forward_delta = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.analog_forward_delta_)}},
    // optional float analog_left_delta = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 4, 0, PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.analog_left_delta_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 button = 1;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.button_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional bool pressed = 2;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.pressed_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional float when = 3;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.when_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float analog_forward_delta = 4;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.analog_forward_delta_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float analog_left_delta = 5;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.analog_left_delta_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float pitch_delta = 8;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.pitch_delta_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float yaw_delta = 9;
    {PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.yaw_delta_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* CSubtickMoveStep::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CSubtickMoveStep)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint64 button = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_button(), target);
  }

  // optional bool pressed = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_pressed(), target);
  }

  // optional float when = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_when(), target);
  }

  // optional float analog_forward_delta = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_analog_forward_delta(), target);
  }

  // optional float analog_left_delta = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_analog_left_delta(), target);
  }

  // optional float pitch_delta = 8;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        8, this->_internal_pitch_delta(), target);
  }

  // optional float yaw_delta = 9;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        9, this->_internal_yaw_delta(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CSubtickMoveStep)
  return target;
}

::size_t CSubtickMoveStep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CSubtickMoveStep)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional uint64 button = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this->_internal_button());
    }

    // optional bool pressed = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2;
    }

    // optional float when = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 5;
    }

    // optional float analog_forward_delta = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 5;
    }

    // optional float analog_left_delta = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 5;
    }

    // optional float pitch_delta = 8;
    if (cached_has_bits & 0x00000020u) {
      total_size += 5;
    }

    // optional float yaw_delta = 9;
    if (cached_has_bits & 0x00000040u) {
      total_size += 5;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CSubtickMoveStep::_class_data_ = {
    CSubtickMoveStep::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CSubtickMoveStep::GetClassData() const {
  return &_class_data_;
}

void CSubtickMoveStep::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CSubtickMoveStep*>(&to_msg);
  auto& from = static_cast<const CSubtickMoveStep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CSubtickMoveStep)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.button_ = from._impl_.button_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.pressed_ = from._impl_.pressed_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.when_ = from._impl_.when_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.analog_forward_delta_ = from._impl_.analog_forward_delta_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.analog_left_delta_ = from._impl_.analog_left_delta_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.pitch_delta_ = from._impl_.pitch_delta_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.yaw_delta_ = from._impl_.yaw_delta_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CSubtickMoveStep::CopyFrom(const CSubtickMoveStep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CSubtickMoveStep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CSubtickMoveStep::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CSubtickMoveStep::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CSubtickMoveStep::InternalSwap(CSubtickMoveStep* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.yaw_delta_)
      + sizeof(CSubtickMoveStep::_impl_.yaw_delta_)
      - PROTOBUF_FIELD_OFFSET(CSubtickMoveStep, _impl_.button_)>(
          reinterpret_cast<char*>(&_impl_.button_),
          reinterpret_cast<char*>(&other->_impl_.button_));
}

::google::protobuf::Metadata CSubtickMoveStep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[1]);
}
// ===================================================================

class CBaseUserCmdExecutionNotes::_Internal {
 public:
  using HasBits = decltype(std::declval<CBaseUserCmdExecutionNotes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CBaseUserCmdExecutionNotes, _impl_._has_bits_);
  static void set_has_ignored_reason(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CBaseUserCmdExecutionNotes::CBaseUserCmdExecutionNotes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CBaseUserCmdExecutionNotes)
}
inline PROTOBUF_NDEBUG_INLINE CBaseUserCmdExecutionNotes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ignored_reason_(arena, from.ignored_reason_) {}

CBaseUserCmdExecutionNotes::CBaseUserCmdExecutionNotes(
    ::google::protobuf::Arena* arena,
    const CBaseUserCmdExecutionNotes& from)
    : ::google::protobuf::Message(arena) {
  CBaseUserCmdExecutionNotes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:CBaseUserCmdExecutionNotes)
}
inline PROTOBUF_NDEBUG_INLINE CBaseUserCmdExecutionNotes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        ignored_reason_(arena) {}

inline void CBaseUserCmdExecutionNotes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CBaseUserCmdExecutionNotes::~CBaseUserCmdExecutionNotes() {
  // @@protoc_insertion_point(destructor:CBaseUserCmdExecutionNotes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CBaseUserCmdExecutionNotes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.ignored_reason_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CBaseUserCmdExecutionNotes::Clear() {
// @@protoc_insertion_point(message_clear_start:CBaseUserCmdExecutionNotes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.ignored_reason_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CBaseUserCmdExecutionNotes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 49, 2> CBaseUserCmdExecutionNotes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CBaseUserCmdExecutionNotes, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CBaseUserCmdExecutionNotes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string ignored_reason = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdExecutionNotes, _impl_.ignored_reason_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string ignored_reason = 1;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdExecutionNotes, _impl_.ignored_reason_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\16\0\0\0\0\0\0"
    "CBaseUserCmdExecutionNotes"
    "ignored_reason"
  }},
};

::uint8_t* CBaseUserCmdExecutionNotes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CBaseUserCmdExecutionNotes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string ignored_reason = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_ignored_reason();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "CBaseUserCmdExecutionNotes.ignored_reason");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CBaseUserCmdExecutionNotes)
  return target;
}

::size_t CBaseUserCmdExecutionNotes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CBaseUserCmdExecutionNotes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string ignored_reason = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_ignored_reason());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CBaseUserCmdExecutionNotes::_class_data_ = {
    CBaseUserCmdExecutionNotes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CBaseUserCmdExecutionNotes::GetClassData() const {
  return &_class_data_;
}

void CBaseUserCmdExecutionNotes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CBaseUserCmdExecutionNotes*>(&to_msg);
  auto& from = static_cast<const CBaseUserCmdExecutionNotes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CBaseUserCmdExecutionNotes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_ignored_reason(from._internal_ignored_reason());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CBaseUserCmdExecutionNotes::CopyFrom(const CBaseUserCmdExecutionNotes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CBaseUserCmdExecutionNotes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CBaseUserCmdExecutionNotes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CBaseUserCmdExecutionNotes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CBaseUserCmdExecutionNotes::InternalSwap(CBaseUserCmdExecutionNotes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ignored_reason_, &other->_impl_.ignored_reason_, arena);
}

::google::protobuf::Metadata CBaseUserCmdExecutionNotes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[2]);
}
// ===================================================================

class CBaseUserCmdPB::_Internal {
 public:
  using HasBits = decltype(std::declval<CBaseUserCmdPB>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_._has_bits_);
  static void set_has_legacy_command_number(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_client_tick(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_prediction_offset_ticks_x256(HasBits* has_bits) {
    (*has_bits)[0] |= 16384u;
  }
  static const ::CInButtonStatePB& buttons_pb(const CBaseUserCmdPB* msg);
  static void set_has_buttons_pb(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::CMsgQAngle& viewangles(const CBaseUserCmdPB* msg);
  static void set_has_viewangles(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_forwardmove(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_leftmove(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_upmove(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_impulse(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_weaponselect(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_random_seed(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_mousedx(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_mousedy(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static void set_has_pawn_entity_handle(HasBits* has_bits) {
    (*has_bits)[0] |= 131072u;
  }
  static void set_has_move_crc(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_consumed_server_angle_changes(HasBits* has_bits) {
    (*has_bits)[0] |= 32768u;
  }
  static void set_has_cmd_flags(HasBits* has_bits) {
    (*has_bits)[0] |= 65536u;
  }
  static const ::CBaseUserCmdExecutionNotes& execution_notes(const CBaseUserCmdPB* msg);
  static void set_has_execution_notes(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::CInButtonStatePB& CBaseUserCmdPB::_Internal::buttons_pb(const CBaseUserCmdPB* msg) {
  return *msg->_impl_.buttons_pb_;
}
const ::CMsgQAngle& CBaseUserCmdPB::_Internal::viewangles(const CBaseUserCmdPB* msg) {
  return *msg->_impl_.viewangles_;
}
const ::CBaseUserCmdExecutionNotes& CBaseUserCmdPB::_Internal::execution_notes(const CBaseUserCmdPB* msg) {
  return *msg->_impl_.execution_notes_;
}
void CBaseUserCmdPB::clear_viewangles() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.viewangles_ != nullptr) _impl_.viewangles_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
CBaseUserCmdPB::CBaseUserCmdPB(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CBaseUserCmdPB)
}
inline PROTOBUF_NDEBUG_INLINE CBaseUserCmdPB::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        subtick_moves_{visibility, arena, from.subtick_moves_},
        move_crc_(arena, from.move_crc_) {}

CBaseUserCmdPB::CBaseUserCmdPB(
    ::google::protobuf::Arena* arena,
    const CBaseUserCmdPB& from)
    : ::google::protobuf::Message(arena) {
  CBaseUserCmdPB* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.buttons_pb_ = (cached_has_bits & 0x00000002u)
                ? CreateMaybeMessage<::CInButtonStatePB>(arena, *from._impl_.buttons_pb_)
                : nullptr;
  _impl_.viewangles_ = (cached_has_bits & 0x00000004u)
                ? CreateMaybeMessage<::CMsgQAngle>(arena, *from._impl_.viewangles_)
                : nullptr;
  _impl_.execution_notes_ = (cached_has_bits & 0x00000008u)
                ? CreateMaybeMessage<::CBaseUserCmdExecutionNotes>(arena, *from._impl_.execution_notes_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, legacy_command_number_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, legacy_command_number_),
           offsetof(Impl_, pawn_entity_handle_) -
               offsetof(Impl_, legacy_command_number_) +
               sizeof(Impl_::pawn_entity_handle_));

  // @@protoc_insertion_point(copy_constructor:CBaseUserCmdPB)
}
inline PROTOBUF_NDEBUG_INLINE CBaseUserCmdPB::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        subtick_moves_{visibility, arena},
        move_crc_(arena),
        pawn_entity_handle_{16777215u} {}

inline void CBaseUserCmdPB::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, buttons_pb_),
           0,
           offsetof(Impl_, cmd_flags_) -
               offsetof(Impl_, buttons_pb_) +
               sizeof(Impl_::cmd_flags_));
}
CBaseUserCmdPB::~CBaseUserCmdPB() {
  // @@protoc_insertion_point(destructor:CBaseUserCmdPB)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CBaseUserCmdPB::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.move_crc_.Destroy();
  delete _impl_.buttons_pb_;
  delete _impl_.viewangles_;
  delete _impl_.execution_notes_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CBaseUserCmdPB::Clear() {
// @@protoc_insertion_point(message_clear_start:CBaseUserCmdPB)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.subtick_moves_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.move_crc_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.buttons_pb_ != nullptr);
      _impl_.buttons_pb_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.viewangles_ != nullptr);
      _impl_.viewangles_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.execution_notes_ != nullptr);
      _impl_.execution_notes_->Clear();
    }
  }
  if (cached_has_bits & 0x000000f0u) {
    ::memset(&_impl_.legacy_command_number_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.leftmove_) -
        reinterpret_cast<char*>(&_impl_.legacy_command_number_)) + sizeof(_impl_.leftmove_));
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&_impl_.upmove_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.consumed_server_angle_changes_) -
        reinterpret_cast<char*>(&_impl_.upmove_)) + sizeof(_impl_.consumed_server_angle_changes_));
  }
  if (cached_has_bits & 0x00030000u) {
    _impl_.cmd_flags_ = 0;
    _impl_.pawn_entity_handle_ = 16777215u;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CBaseUserCmdPB::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 19, 4, 0, 2> CBaseUserCmdPB::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_._has_bits_),
    0, // no _extensions_
    22, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4290826240,  // skipmap
    offsetof(decltype(_table_), field_entries),
    19,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CBaseUserCmdPB_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 legacy_command_number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.legacy_command_number_), 4>(),
     {8, 4, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.legacy_command_number_)}},
    // optional int32 client_tick = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.client_tick_), 5>(),
     {16, 5, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.client_tick_)}},
    // optional .CInButtonStatePB buttons_pb = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.buttons_pb_)}},
    // optional .CMsgQAngle viewangles = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 1, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.viewangles_)}},
    // optional float forwardmove = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 6, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.forwardmove_)}},
    // optional float leftmove = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 7, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.leftmove_)}},
    // optional float upmove = 7;
    {::_pbi::TcParser::FastF32S1,
     {61, 8, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.upmove_)}},
    // optional int32 impulse = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.impulse_), 9>(),
     {64, 9, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.impulse_)}},
    // optional int32 weaponselect = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.weaponselect_), 10>(),
     {72, 10, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.weaponselect_)}},
    // optional int32 random_seed = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.random_seed_), 11>(),
     {80, 11, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.random_seed_)}},
    // optional int32 mousedx = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.mousedx_), 12>(),
     {88, 12, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedx_)}},
    // optional int32 mousedy = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.mousedy_), 13>(),
     {96, 13, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedy_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 pawn_entity_handle = 14 [default = 16777215];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CBaseUserCmdPB, _impl_.pawn_entity_handle_), 17>(),
     {112, 17, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.pawn_entity_handle_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 prediction_offset_ticks_x256 = 17;
    {::_pbi::TcParser::FastV32S2,
     {392, 14, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.prediction_offset_ticks_x256_)}},
    // repeated .CSubtickMoveStep subtick_moves = 18;
    {::_pbi::TcParser::FastMtR2,
     {402, 63, 2, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.subtick_moves_)}},
    // optional bytes move_crc = 19;
    {::_pbi::TcParser::FastBS2,
     {410, 0, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.move_crc_)}},
    // optional uint32 consumed_server_angle_changes = 20;
    {::_pbi::TcParser::FastV32S2,
     {416, 15, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.consumed_server_angle_changes_)}},
    // optional int32 cmd_flags = 21;
    {::_pbi::TcParser::FastV32S2,
     {424, 16, 0, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.cmd_flags_)}},
    // optional .CBaseUserCmdExecutionNotes execution_notes = 22;
    {::_pbi::TcParser::FastMtS2,
     {434, 3, 3, PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.execution_notes_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 legacy_command_number = 1;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.legacy_command_number_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 client_tick = 2;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.client_tick_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .CInButtonStatePB buttons_pb = 3;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.buttons_pb_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .CMsgQAngle viewangles = 4;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.viewangles_), _Internal::kHasBitsOffset + 2, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional float forwardmove = 5;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.forwardmove_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float leftmove = 6;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.leftmove_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float upmove = 7;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.upmove_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional int32 impulse = 8;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.impulse_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 weaponselect = 9;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.weaponselect_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 random_seed = 10;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.random_seed_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 mousedx = 11;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedx_), _Internal::kHasBitsOffset + 12, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 mousedy = 12;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.mousedy_), _Internal::kHasBitsOffset + 13, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint32 pawn_entity_handle = 14 [default = 16777215];
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.pawn_entity_handle_), _Internal::kHasBitsOffset + 17, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 prediction_offset_ticks_x256 = 17;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.prediction_offset_ticks_x256_), _Internal::kHasBitsOffset + 14, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated .CSubtickMoveStep subtick_moves = 18;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.subtick_moves_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bytes move_crc = 19;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.move_crc_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 consumed_server_angle_changes = 20;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.consumed_server_angle_changes_), _Internal::kHasBitsOffset + 15, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional int32 cmd_flags = 21;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.cmd_flags_), _Internal::kHasBitsOffset + 16, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .CBaseUserCmdExecutionNotes execution_notes = 22;
    {PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.execution_notes_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::CInButtonStatePB>()},
    {::_pbi::TcParser::GetTable<::CMsgQAngle>()},
    {::_pbi::TcParser::GetTable<::CSubtickMoveStep>()},
    {::_pbi::TcParser::GetTable<::CBaseUserCmdExecutionNotes>()},
  }}, {{
  }},
};

::uint8_t* CBaseUserCmdPB::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CBaseUserCmdPB)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 legacy_command_number = 1;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_legacy_command_number(), target);
  }

  // optional int32 client_tick = 2;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_client_tick(), target);
  }

  // optional .CInButtonStatePB buttons_pb = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, _Internal::buttons_pb(this),
        _Internal::buttons_pb(this).GetCachedSize(), target, stream);
  }

  // optional .CMsgQAngle viewangles = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::viewangles(this),
        _Internal::viewangles(this).GetCachedSize(), target, stream);
  }

  // optional float forwardmove = 5;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_forwardmove(), target);
  }

  // optional float leftmove = 6;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this->_internal_leftmove(), target);
  }

  // optional float upmove = 7;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        7, this->_internal_upmove(), target);
  }

  // optional int32 impulse = 8;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<8>(
            stream, this->_internal_impulse(), target);
  }

  // optional int32 weaponselect = 9;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<9>(
            stream, this->_internal_weaponselect(), target);
  }

  // optional int32 random_seed = 10;
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<10>(
            stream, this->_internal_random_seed(), target);
  }

  // optional int32 mousedx = 11;
  if (cached_has_bits & 0x00001000u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<11>(
            stream, this->_internal_mousedx(), target);
  }

  // optional int32 mousedy = 12;
  if (cached_has_bits & 0x00002000u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<12>(
            stream, this->_internal_mousedy(), target);
  }

  // optional uint32 pawn_entity_handle = 14 [default = 16777215];
  if (cached_has_bits & 0x00020000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        14, this->_internal_pawn_entity_handle(), target);
  }

  // optional uint32 prediction_offset_ticks_x256 = 17;
  if (cached_has_bits & 0x00004000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        17, this->_internal_prediction_offset_ticks_x256(), target);
  }

  // repeated .CSubtickMoveStep subtick_moves = 18;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_subtick_moves_size()); i < n; i++) {
    const auto& repfield = this->_internal_subtick_moves().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(18, repfield, repfield.GetCachedSize(), target, stream);
  }

  // optional bytes move_crc = 19;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_move_crc();
    target = stream->WriteBytesMaybeAliased(19, _s, target);
  }

  // optional uint32 consumed_server_angle_changes = 20;
  if (cached_has_bits & 0x00008000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        20, this->_internal_consumed_server_angle_changes(), target);
  }

  // optional int32 cmd_flags = 21;
  if (cached_has_bits & 0x00010000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        21, this->_internal_cmd_flags(), target);
  }

  // optional .CBaseUserCmdExecutionNotes execution_notes = 22;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        22, _Internal::execution_notes(this),
        _Internal::execution_notes(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CBaseUserCmdPB)
  return target;
}

::size_t CBaseUserCmdPB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CBaseUserCmdPB)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CSubtickMoveStep subtick_moves = 18;
  total_size += 2UL * this->_internal_subtick_moves_size();
  for (const auto& msg : this->_internal_subtick_moves()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes move_crc = 19;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_move_crc());
    }

    // optional .CInButtonStatePB buttons_pb = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.buttons_pb_);
    }

    // optional .CMsgQAngle viewangles = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.viewangles_);
    }

    // optional .CBaseUserCmdExecutionNotes execution_notes = 22;
    if (cached_has_bits & 0x00000008u) {
      total_size +=
          2 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.execution_notes_);
    }

    // optional int32 legacy_command_number = 1;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_legacy_command_number());
    }

    // optional int32 client_tick = 2;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_client_tick());
    }

    // optional float forwardmove = 5;
    if (cached_has_bits & 0x00000040u) {
      total_size += 5;
    }

    // optional float leftmove = 6;
    if (cached_has_bits & 0x00000080u) {
      total_size += 5;
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional float upmove = 7;
    if (cached_has_bits & 0x00000100u) {
      total_size += 5;
    }

    // optional int32 impulse = 8;
    if (cached_has_bits & 0x00000200u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_impulse());
    }

    // optional int32 weaponselect = 9;
    if (cached_has_bits & 0x00000400u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_weaponselect());
    }

    // optional int32 random_seed = 10;
    if (cached_has_bits & 0x00000800u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_random_seed());
    }

    // optional int32 mousedx = 11;
    if (cached_has_bits & 0x00001000u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_mousedx());
    }

    // optional int32 mousedy = 12;
    if (cached_has_bits & 0x00002000u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_mousedy());
    }

    // optional uint32 prediction_offset_ticks_x256 = 17;
    if (cached_has_bits & 0x00004000u) {
      total_size += 2 + ::_pbi::WireFormatLite::UInt32Size(
                                      this->_internal_prediction_offset_ticks_x256());
    }

    // optional uint32 consumed_server_angle_changes = 20;
    if (cached_has_bits & 0x00008000u) {
      total_size += 2 + ::_pbi::WireFormatLite::UInt32Size(
                                      this->_internal_consumed_server_angle_changes());
    }

  }
  if (cached_has_bits & 0x00030000u) {
    // optional int32 cmd_flags = 21;
    if (cached_has_bits & 0x00010000u) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this->_internal_cmd_flags());
    }

    // optional uint32 pawn_entity_handle = 14 [default = 16777215];
    if (cached_has_bits & 0x00020000u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_pawn_entity_handle());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CBaseUserCmdPB::_class_data_ = {
    CBaseUserCmdPB::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CBaseUserCmdPB::GetClassData() const {
  return &_class_data_;
}

void CBaseUserCmdPB::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CBaseUserCmdPB*>(&to_msg);
  auto& from = static_cast<const CBaseUserCmdPB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CBaseUserCmdPB)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_subtick_moves()->MergeFrom(
      from._internal_subtick_moves());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_move_crc(from._internal_move_crc());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_buttons_pb()->::CInButtonStatePB::MergeFrom(
          from._internal_buttons_pb());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_viewangles()->::CMsgQAngle::MergeFrom(
          from._internal_viewangles());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_mutable_execution_notes()->::CBaseUserCmdExecutionNotes::MergeFrom(
          from._internal_execution_notes());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.legacy_command_number_ = from._impl_.legacy_command_number_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.client_tick_ = from._impl_.client_tick_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.forwardmove_ = from._impl_.forwardmove_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.leftmove_ = from._impl_.leftmove_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_impl_.upmove_ = from._impl_.upmove_;
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.impulse_ = from._impl_.impulse_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.weaponselect_ = from._impl_.weaponselect_;
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.random_seed_ = from._impl_.random_seed_;
    }
    if (cached_has_bits & 0x00001000u) {
      _this->_impl_.mousedx_ = from._impl_.mousedx_;
    }
    if (cached_has_bits & 0x00002000u) {
      _this->_impl_.mousedy_ = from._impl_.mousedy_;
    }
    if (cached_has_bits & 0x00004000u) {
      _this->_impl_.prediction_offset_ticks_x256_ = from._impl_.prediction_offset_ticks_x256_;
    }
    if (cached_has_bits & 0x00008000u) {
      _this->_impl_.consumed_server_angle_changes_ = from._impl_.consumed_server_angle_changes_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00030000u) {
    if (cached_has_bits & 0x00010000u) {
      _this->_impl_.cmd_flags_ = from._impl_.cmd_flags_;
    }
    if (cached_has_bits & 0x00020000u) {
      _this->_impl_.pawn_entity_handle_ = from._impl_.pawn_entity_handle_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CBaseUserCmdPB::CopyFrom(const CBaseUserCmdPB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CBaseUserCmdPB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CBaseUserCmdPB::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CBaseUserCmdPB::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CBaseUserCmdPB::InternalSwap(CBaseUserCmdPB* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.subtick_moves_.InternalSwap(&other->_impl_.subtick_moves_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.move_crc_, &other->_impl_.move_crc_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.pawn_entity_handle_)
      + sizeof(CBaseUserCmdPB::_impl_.pawn_entity_handle_)
      - PROTOBUF_FIELD_OFFSET(CBaseUserCmdPB, _impl_.buttons_pb_)>(
          reinterpret_cast<char*>(&_impl_.buttons_pb_),
          reinterpret_cast<char*>(&other->_impl_.buttons_pb_));
}

::google::protobuf::Metadata CBaseUserCmdPB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[3]);
}
// ===================================================================

class CUserCmdBasePB::_Internal {
 public:
  using HasBits = decltype(std::declval<CUserCmdBasePB>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_._has_bits_);
  static const ::CBaseUserCmdPB& base(const CUserCmdBasePB* msg);
  static void set_has_base(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::CBaseUserCmdPB& CUserCmdBasePB::_Internal::base(const CUserCmdBasePB* msg) {
  return *msg->_impl_.base_;
}
CUserCmdBasePB::CUserCmdBasePB(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CUserCmdBasePB)
}
inline PROTOBUF_NDEBUG_INLINE CUserCmdBasePB::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CUserCmdBasePB::CUserCmdBasePB(
    ::google::protobuf::Arena* arena,
    const CUserCmdBasePB& from)
    : ::google::protobuf::Message(arena) {
  CUserCmdBasePB* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.base_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::CBaseUserCmdPB>(arena, *from._impl_.base_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:CUserCmdBasePB)
}
inline PROTOBUF_NDEBUG_INLINE CUserCmdBasePB::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CUserCmdBasePB::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.base_ = {};
}
CUserCmdBasePB::~CUserCmdBasePB() {
  // @@protoc_insertion_point(destructor:CUserCmdBasePB)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CUserCmdBasePB::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.base_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void CUserCmdBasePB::Clear() {
// @@protoc_insertion_point(message_clear_start:CUserCmdBasePB)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.base_ != nullptr);
    _impl_.base_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* CUserCmdBasePB::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> CUserCmdBasePB::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CUserCmdBasePB_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional .CBaseUserCmdPB base = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_.base_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .CBaseUserCmdPB base = 1;
    {PROTOBUF_FIELD_OFFSET(CUserCmdBasePB, _impl_.base_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::CBaseUserCmdPB>()},
  }}, {{
  }},
};

::uint8_t* CUserCmdBasePB::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CUserCmdBasePB)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .CBaseUserCmdPB base = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::base(this),
        _Internal::base(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUserCmdBasePB)
  return target;
}

::size_t CUserCmdBasePB::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CUserCmdBasePB)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .CBaseUserCmdPB base = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.base_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData CUserCmdBasePB::_class_data_ = {
    CUserCmdBasePB::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* CUserCmdBasePB::GetClassData() const {
  return &_class_data_;
}

void CUserCmdBasePB::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<CUserCmdBasePB*>(&to_msg);
  auto& from = static_cast<const CUserCmdBasePB&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CUserCmdBasePB)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_base()->::CBaseUserCmdPB::MergeFrom(
        from._internal_base());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CUserCmdBasePB::CopyFrom(const CUserCmdBasePB& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CUserCmdBasePB)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool CUserCmdBasePB::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* CUserCmdBasePB::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void CUserCmdBasePB::InternalSwap(CUserCmdBasePB* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.base_, other->_impl_.base_);
}

::google::protobuf::Metadata CUserCmdBasePB::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_usercmd_2eproto_getter, &descriptor_table_usercmd_2eproto_once,
      file_level_metadata_usercmd_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
